In [22]:
import glob
import numpy as np

from astropy.table  import Table

from desitarget.io  import read_mtl_ledger
from desitarget.mtl import make_mtl, inflate_ledger

# Original documentation

https://github.com/desihub/desitarget/pull/635


Grab a starting targets file.

In [4]:
# Standard target files, hp 39 only.
targets = Table.read('/project/projectdirs/desi/target/catalogs/dr8/0.39.0/targets/sv/resolve//dark/sv1-targets-dr8-hp-39.fits')

In [5]:
targets

<Table length=1178683>
RELEASE BRICKID BRICKNAME BRICK_OBJID ... PRIORITY_INIT NUMOBS_INIT HPXPIXEL
 int16   int32    bytes8     int32    ...     int64        int64     int64  
------- ------- --------- ----------- ... ------------- ----------- --------
   8000  323702  1336m012        5007 ...          1050           1    40958
   8000  325152  1361m010        2375 ...          1050           1    40957
   8000  279285  1454m090          63 ...          1050           1    40789
   8000  279283  1449m090           6 ...          1050           1    40791
   8000  279283  1449m090          31 ...          1100           1    40791
   8000  279282  1447m090         294 ...          1100           1    40791
   8000  279282  1447m090         295 ...          1100           1    40791
   8000  279282  1447m090          45 ...          1100           1    40791
   8000  279282  1447m090         199 ...          1050           1    40791
   8000  279282  1447m090         526 ...          1100           1    40791
    ...     ...       ...         ... ...           ...         ...      ...
   8000  317937  1323m022        4440 ...          3000           1    40954
   8000  317937  1323m022        4528 ...          3000           1    40954
   8000  317937  1323m022        4536 ...          3000           1    40954
   8000  317937  1323m022        4621 ...          3200           4    40954
   8000  317937  1323m022        4622 ...          3400           4    40954
   8000  317937  1323m022        4637 ...          3000           1    40954
   8000  317937  1323m022        4782 ...          3000           1    40954
   8000  317937  1323m022        4895 ...          3000           1    40954
   8000  317937  1323m022        4921 ...          3000           1    40954
   8000  317937  1323m022        4922 ...          3000           1    40954

Call to create a ledger from the targets:

In [ ]:
# ! make_ledger('/project/projectdirs/desi/target/catalogs/dr8/0.39.0/targets/sv/resolve/dark/', '/global/cscratch1/sd/adamyers/egledger/mtl/sv1/dark/', obscon="DARK", numproc=1)

Retrieve a pre-created version, or run above, which ones are available?

In [23]:
ledgers = glob.glob('/global/cscratch1/sd/adamyers/egledger/mtl/sv1/dark/*.ecsv')

In [25]:
ledgers[:10]

['/global/cscratch1/sd/adamyers/egledger/mtl/sv1/dark/sv1mtl-dark-hp-4282.ecsv',
 '/global/cscratch1/sd/adamyers/egledger/mtl/sv1/dark/sv1mtl-dark-hp-4923.ecsv',
 '/global/cscratch1/sd/adamyers/egledger/mtl/sv1/dark/sv1mtl-dark-hp-8442.ecsv',
 '/global/cscratch1/sd/adamyers/egledger/mtl/sv1/dark/sv1mtl-dark-hp-8156.ecsv',
 '/global/cscratch1/sd/adamyers/egledger/mtl/sv1/dark/sv1mtl-dark-hp-2237.ecsv',
 '/global/cscratch1/sd/adamyers/egledger/mtl/sv1/dark/sv1mtl-dark-hp-1974.ecsv',
 '/global/cscratch1/sd/adamyers/egledger/mtl/sv1/dark/sv1mtl-dark-hp-5036.ecsv',
 '/global/cscratch1/sd/adamyers/egledger/mtl/sv1/dark/sv1mtl-dark-hp-2683.ecsv',
 '/global/cscratch1/sd/adamyers/egledger/mtl/sv1/dark/sv1mtl-dark-hp-6481.ecsv',
 '/global/cscratch1/sd/adamyers/egledger/mtl/sv1/dark/sv1mtl-dark-hp-4765.ecsv']

In [41]:
# Only healpixels with targets are processed.
hpxls = np.array([x.split('-')[-1].replace('.ecsv', '') for x in ledgers]).astype(np.int)
hpxls = np.unique(hpxls)

In [42]:
hpxls

array([    0,     1,     2, ..., 12285, 12286, 12287])

In [68]:
# HEALPixel-split ledger files generated from the standard target files.
# A new data model that includes a state for each target, a timestamp for when a target's state was updated,
# and the desitarget code version that was used to update the target's state.
ledger = read_mtl_ledger('/global/cscratch1/sd/adamyers/egledger/mtl/sv1/dark/sv1mtl-dark-hp-8400.ecsv')

In [69]:
ledger = Table(ledger)
ledger

<Table length=33457>
        RA                 DEC         REF_EPOCH ...    VERSION     PRIORITY
     float64             float64        float32  ...    bytes14      int64  
------------------ ------------------- --------- ... -------------- --------
54.001323804796705  -60.42569957270399       0.0 ... 0.40.0.dev4055     2000
 53.98978693990547  -60.42437965201657       0.0 ... 0.40.0.dev4055     2000
 54.00065664480867 -60.413051892093264    2015.5 ... 0.40.0.dev4055     1100
 54.00388319697416  -60.40578902819227       0.0 ... 0.40.0.dev4055     3000
 54.02399665690195  -60.40574510577453       0.0 ... 0.40.0.dev4055     3000
  54.0096905775631  -60.40490529851805       0.0 ... 0.40.0.dev4055     3200
 53.98612145219522  -60.40042332596103       0.0 ... 0.40.0.dev4055     3000
 54.03456513256729  -60.39866568329702       0.0 ... 0.40.0.dev4055     3000
 54.04106232591186  -60.39820885464255       0.0 ... 0.40.0.dev4055     3000
 53.94972457303881  -60.39871565989709       0.0 ... 0.40.0.dev4055     3000
               ...                 ...       ... ...            ...      ...
53.239385487001556  -57.46004639475924       0.0 ... 0.40.0.dev4055     3200
  53.2381880610812  -57.46089657690123       0.0 ... 0.40.0.dev4055     3000
53.255121294063855 -57.448343676891696    2015.5 ... 0.40.0.dev4055     1100
53.241935031743175  -57.44719228751675       0.0 ... 0.40.0.dev4055     3000
53.256068059790856  -57.44627105068773       0.0 ... 0.40.0.dev4055     3000
 53.22481970787932  -57.44482766879436       0.0 ... 0.40.0.dev4055     3000
  53.2196836492193  -57.44343901374039       0.0 ... 0.40.0.dev4055     3000
 53.23663483568959   -57.4418668856492       0.0 ... 0.40.0.dev4055     2000
53.239949245851115 -57.443590486737726       0.0 ... 0.40.0.dev4055     3000
53.228672712566656  -57.44146976151331    2015.5 ... 0.40.0.dev4055     1050

In [70]:
uids, cnts = np.unique(ledger['TARGETID'], return_counts=True)

In [71]:
# Initialised ledger.
np.unique(cnts)

array([1])

In [72]:
# Does this match up with fiberassign input arguments?  Did this rundate change?  Now YYYY-MM-DD.
ledger['TIMESTAMP']

<Column name='TIMESTAMP' dtype='bytes19' length=33457>
2020-08-03T22:15:36
2020-08-03T22:15:36
2020-08-03T22:15:36
2020-08-03T22:15:36
2020-08-03T22:15:36
2020-08-03T22:15:36
2020-08-03T22:15:36
2020-08-03T22:15:36
2020-08-03T22:15:36
2020-08-03T22:15:36
2020-08-03T22:15:36
2020-08-03T22:15:36
                ...
2020-08-03T22:15:36
2020-08-03T22:15:36
2020-08-03T22:15:36
2020-08-03T22:15:36
2020-08-03T22:15:36
2020-08-03T22:15:36
2020-08-03T22:15:36
2020-08-03T22:15:36
2020-08-03T22:15:36
2020-08-03T22:15:36
2020-08-03T22:15:36
2020-08-03T22:15:36

In [73]:
ledger['VERSION']

<Column name='VERSION' dtype='bytes14' length=33457>
0.40.0.dev4055
0.40.0.dev4055
0.40.0.dev4055
0.40.0.dev4055
0.40.0.dev4055
0.40.0.dev4055
0.40.0.dev4055
0.40.0.dev4055
0.40.0.dev4055
0.40.0.dev4055
0.40.0.dev4055
0.40.0.dev4055
           ...
0.40.0.dev4055
0.40.0.dev4055
0.40.0.dev4055
0.40.0.dev4055
0.40.0.dev4055
0.40.0.dev4055
0.40.0.dev4055
0.40.0.dev4055
0.40.0.dev4055
0.40.0.dev4055
0.40.0.dev4055
0.40.0.dev4055

Create a (now default slimmed) mtl from the ledger files:

In [74]:
# Columns are now automatically trimmed to a minimum necessary set in desitarget.mtl.make_mtl()
mtl = make_mtl(ledger, obscon='DARK')

INFO:mtl.py:230:make_mtl: 11 of 33457 targets have priority zero, setting N_obs=0.
INFO:mtl.py:293:make_mtl: Done...t=0.1s


In [75]:
# TIMESTAMP -> LAST_TIMESTAMP?
mtl

<Table length=33457>
        RA                 DEC         REF_EPOCH ...    VERSION     PRIORITY
     float64             float64        float32  ...    bytes14      int64  
------------------ ------------------- --------- ... -------------- --------
54.001323804796705  -60.42569957270399       0.0 ... 0.43.0.dev4234     2000
 53.98978693990547  -60.42437965201657       0.0 ... 0.43.0.dev4234     2000
 54.00065664480867 -60.413051892093264    2015.5 ... 0.43.0.dev4234     1100
 54.00388319697416  -60.40578902819227       0.0 ... 0.43.0.dev4234     3000
 54.02399665690195  -60.40574510577453       0.0 ... 0.43.0.dev4234     3000
  54.0096905775631  -60.40490529851805       0.0 ... 0.43.0.dev4234     3200
 53.98612145219522  -60.40042332596103       0.0 ... 0.43.0.dev4234     3000
 54.03456513256729  -60.39866568329702       0.0 ... 0.43.0.dev4234     3000
 54.04106232591186  -60.39820885464255       0.0 ... 0.43.0.dev4234     3000
 53.94972457303881  -60.39871565989709       0.0 ... 0.43.0.dev4234     3000
               ...                 ...       ... ...            ...      ...
53.239385487001556  -57.46004639475924       0.0 ... 0.43.0.dev4234     3200
  53.2381880610812  -57.46089657690123       0.0 ... 0.43.0.dev4234     3000
53.255121294063855 -57.448343676891696    2015.5 ... 0.43.0.dev4234     1100
53.241935031743175  -57.44719228751675       0.0 ... 0.43.0.dev4234     3000
53.256068059790856  -57.44627105068773       0.0 ... 0.43.0.dev4234     3000
 53.22481970787932  -57.44482766879436       0.0 ... 0.43.0.dev4234     3000
  53.2196836492193  -57.44343901374039       0.0 ... 0.43.0.dev4234     3000
 53.23663483568959   -57.4418668856492       0.0 ... 0.43.0.dev4234     2000
53.239949245851115 -57.443590486737726       0.0 ... 0.43.0.dev4234     3000
53.228672712566656  -57.44146976151331    2015.5 ... 0.43.0.dev4234     1050

Each TARGETID only appears once in the mtl, with the latest state:

In [76]:
uids, cnts = np.unique(mtl['TARGETID'], return_counts=True)

In [77]:
cnts.max()

1

In [78]:
imtl = inflate_ledger(mtl, '/project/projectdirs/desi/target/catalogs/dr8/0.39.0/targets/sv/resolve//dark/', columns=None, header=False, strictcols=False)

In [79]:
len(imtl.dtype.names), len(mtl.dtype.names)

(115, 23)

New columns in inflated ledger:

In [80]:
[x for x in list(imtl.dtype.names) if x not in list(mtl.dtype.names)]

['RELEASE',
 'BRICKID',
 'BRICKNAME',
 'BRICK_OBJID',
 'MORPHTYPE',
 'RA_IVAR',
 'DEC_IVAR',
 'DCHISQ',
 'EBV',
 'FLUX_G',
 'FLUX_R',
 'FLUX_Z',
 'FLUX_IVAR_G',
 'FLUX_IVAR_R',
 'FLUX_IVAR_Z',
 'MW_TRANSMISSION_G',
 'MW_TRANSMISSION_R',
 'MW_TRANSMISSION_Z',
 'FRACFLUX_G',
 'FRACFLUX_R',
 'FRACFLUX_Z',
 'FRACMASKED_G',
 'FRACMASKED_R',
 'FRACMASKED_Z',
 'FRACIN_G',
 'FRACIN_R',
 'FRACIN_Z',
 'NOBS_G',
 'NOBS_R',
 'NOBS_Z',
 'PSFDEPTH_G',
 'PSFDEPTH_R',
 'PSFDEPTH_Z',
 'GALDEPTH_G',
 'GALDEPTH_R',
 'GALDEPTH_Z',
 'FLUX_W1',
 'FLUX_W2',
 'FLUX_W3',
 'FLUX_W4',
 'FLUX_IVAR_W1',
 'FLUX_IVAR_W2',
 'FLUX_IVAR_W3',
 'FLUX_IVAR_W4',
 'MW_TRANSMISSION_W1',
 'MW_TRANSMISSION_W2',
 'MW_TRANSMISSION_W3',
 'MW_TRANSMISSION_W4',
 'ALLMASK_G',
 'ALLMASK_R',
 'ALLMASK_Z',
 'FIBERFLUX_G',
 'FIBERFLUX_R',
 'FIBERFLUX_Z',
 'FIBERTOTFLUX_G',
 'FIBERTOTFLUX_R',
 'FIBERTOTFLUX_Z',
 'WISEMASK_W1',
 'WISEMASK_W2',
 'MASKBITS',
 'FRACDEV',
 'FRACDEV_IVAR',
 'SHAPEDEV_R',
 'SHAPEDEV_E1',
 'SHAPEDEV_E2',
 'SHAPE

In [81]:
ledger_updates = glob.glob('/global/cscratch1/sd/adamyers/egupdates/mtl/sv1/dark/*.ecsv')

In [82]:
ledger_updates[:10]

['/global/cscratch1/sd/adamyers/egupdates/mtl/sv1/dark/sv1mtl-dark-hp-8442.ecsv',
 '/global/cscratch1/sd/adamyers/egupdates/mtl/sv1/dark/sv1mtl-dark-hp-8411.ecsv',
 '/global/cscratch1/sd/adamyers/egupdates/mtl/sv1/dark/sv1mtl-dark-hp-8588.ecsv',
 '/global/cscratch1/sd/adamyers/egupdates/mtl/sv1/dark/sv1mtl-dark-hp-8705.ecsv',
 '/global/cscratch1/sd/adamyers/egupdates/mtl/sv1/dark/sv1mtl-dark-hp-8713.ecsv',
 '/global/cscratch1/sd/adamyers/egupdates/mtl/sv1/dark/sv1mtl-dark-hp-8669.ecsv',
 '/global/cscratch1/sd/adamyers/egupdates/mtl/sv1/dark/sv1mtl-dark-hp-8733.ecsv',
 '/global/cscratch1/sd/adamyers/egupdates/mtl/sv1/dark/sv1mtl-dark-hp-8440.ecsv',
 '/global/cscratch1/sd/adamyers/egupdates/mtl/sv1/dark/sv1mtl-dark-hp-8441.ecsv',
 '/global/cscratch1/sd/adamyers/egupdates/mtl/sv1/dark/sv1mtl-dark-hp-8503.ecsv']

In [105]:
update = read_mtl_ledger('/global/cscratch1/sd/adamyers/egupdates/mtl/sv1/dark/sv1mtl-dark-hp-8400.ecsv')

In [106]:
update = Table(update)

In [107]:
update

<Table length=33457>
        RA                 DEC         REF_EPOCH ...    VERSION     PRIORITY
     float64             float64        float32  ...    bytes14      int64  
------------------ ------------------- --------- ... -------------- --------
54.001323804796705  -60.42569957270399       0.0 ... 0.40.0.dev4055     2000
 53.98978693990547  -60.42437965201657       0.0 ... 0.40.0.dev4055     2000
 54.00065664480867 -60.413051892093264    2015.5 ... 0.40.0.dev4055     1100
 54.00388319697416  -60.40578902819227       0.0 ... 0.40.0.dev4055     3000
 54.02399665690195  -60.40574510577453       0.0 ... 0.40.0.dev4055     3000
  54.0096905775631  -60.40490529851805       0.0 ... 0.40.0.dev4055     3200
 53.98612145219522  -60.40042332596103       0.0 ... 0.40.0.dev4055     3000
 54.03456513256729  -60.39866568329702       0.0 ... 0.40.0.dev4055     3000
 54.04106232591186  -60.39820885464255       0.0 ... 0.40.0.dev4055     3000
 53.94972457303881  -60.39871565989709       0.0 ... 0.40.0.dev4055     3000
               ...                 ...       ... ...            ...      ...
53.239385487001556  -57.46004639475924       0.0 ... 0.40.0.dev4055     3200
  53.2381880610812  -57.46089657690123       0.0 ... 0.40.0.dev4055     3000
53.255121294063855 -57.448343676891696    2015.5 ... 0.40.0.dev4055     1100
53.241935031743175  -57.44719228751675       0.0 ... 0.40.0.dev4055     3000
53.256068059790856  -57.44627105068773       0.0 ... 0.40.0.dev4055     3000
 53.22481970787932  -57.44482766879436       0.0 ... 0.40.0.dev4055     3000
  53.2196836492193  -57.44343901374039       0.0 ... 0.40.0.dev4055     3000
 53.23663483568959   -57.4418668856492       0.0 ... 0.40.0.dev4055     2000
53.239949245851115 -57.443590486737726       0.0 ... 0.40.0.dev4055     3000
53.228672712566656  -57.44146976151331    2015.5 ... 0.40.0.dev4055     1050

In [108]:
uids, cnts = np.unique(update['TARGETID'], return_counts=True) 

In [109]:
np.unique(cnts)

array([1])

In [110]:
np.unique(update['NUMOBS'])

<Column name='NUMOBS' dtype='int64' length=1>
0

# Done.